### ISSUE TITLE
Consider connecting to the fediverse

### ISSUE THREAD

**Issue by GrosSacASac** [dan-divy/spruce#12]
https://peertube.social/videos/watch/d9bd2ee9-b7a4-44e3-8d65-61badd15c6e6
ActivityPub https://www.w3.org/TR/activitypub/

**Comment by DivySrivastava** [comment]
Wonderful! Soon start working on that...

**Comment by DivySrivastava** [comment]
I had no idea about activity streams..
Please tell me how to implement them on Nodejs

**Comment by GrosSacASac** [comment]
I can help you later this weekend, I am also new to this topic so I am reading the documentation still.

**Comment by GrosSacASac** [comment]
Some notes, as far as I understand:

To be activitypub compatible we need to have an HTTP endpoints that accepts  well defined POST GET requests
with an activity as the body.

An activity or action  defined http://w3c.github.io/activitystreams/core/

```
uses   MIME media type "application/activity+json"
is encoded with utf-8
is a JSON-LD with a context "https://www.w3.org/ns/activitystreams"

the time format  used is defined https://tools.ietf.org/html/rfc3339#section-5.6
(seconds may be omitted)
for example 2019-05-23T16:00:01Z
```

vocabulary is defined https://w3c.github.io/activitystreams/vocabulary/

example:

```
const activity = {
  "@context": "https://www.w3.org/ns/activitystreams",
  "summary": "A note",
  "type": "Note",
  "content": "My dog has fleas."
};
```

**Comment by DivySrivastava** [comment]
Well,
I got this https://github.com/GetStream/stream-node-orm

**Comment by MayorChano** [comment]
@GrosSacASac you are also welcome to create a pr and we can work on this there

**Comment by GrosSacASac** [comment]
Thanks, I don't have much time in the near future but I'll see what I can do

**Comment by MayorChano** [comment]
I'll close this issue for now but we can always revisit this later!
