### ISSUE TITLE
empty event page

### ISSUE THREAD

**Issue by tjskrish** [dan-divy/spruce#20]
- Event page empty
- Designs to follow

**Comment by MayorChano** [comment]
Could you elaborate?

**Comment by DivySrivastava** [comment]
The event page is empty because there is no post that is tagged as `event`.
Please upload a post tagged as an event and then check.
Your second point doesn't make sense.

**Comment by tjskrish** [comment]
Events:
- Ability to specify location 
- Ability to add people/group to an event

**Comment by DivySrivastava** [comment]
@tjskrish Please create a PR

**Comment by MayorChano** [comment]
@tjskrish Do you mind either explaining what you meant or creating a PR otherwise we will close this issue. Thanks!

**Comment by DivySrivastava** [comment]
Closing this issue due to inadequate information provided by @tjskrish
