### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by amitbend** [dan-divy/spruce#29]
Hey, I tried to see your demo but it seems to be down.

**Comment by MayorChano** [comment]
@amitbend It is currently experiencing problems but [here](https://spruce.dancodes.online) is a working example

**Comment by MayorChano** [comment]
I've updates the readme and the repo in [this](https://github.com/dan-divy/spruce/commit/448cbdb6ce61bfda2285ec7d8d63f5a60047599c) commit

**Comment by amitbend** [comment]
Great, thanks!
