### ISSUE TITLE
Is there any API for all features? 

### ISSUE THREAD

**Issue by thiyaga24** [dan-divy/spruce#31]
Hi, This is just an question. please tag.
please let me know whether there is any API for all features like browsing feeds etc., If so, Please provide me pointers for the same
We are looking for mobile-first social-networking platform. It seems spruce better suits this case.

**Comment by DivySrivastava** [comment]
@thiyaga We don't have any sort of public api yet.
As per the plan, we have to add a restApi.
Will definetly start work on that!
You are most welcome to create a PR!
Inbox me for support on this

Regards,
Divy Srivastava

**Comment by DivySrivastava** [comment]
@thiyaga24 We don't have any sort of public api yet.
As per the plan, we have to add a restApi.
Will definetly start work on that!
You are most welcome to create a PR!
Inbox me for support on this

Regards,
Divy Srivastava

**Comment by dan-online** [comment]
@thiyaga24 Technically we have an api which is used by the webapp to
- post
- like 
and etc but a public API is yet to come. As @DivySrivastava said, feel free to create a PR

Regards

Dan

**Comment by DivySrivastava** [comment]
@thiyaga24 We are adding a public API feature currently in the `rewrite` branch.

Fell free to contribute there.

Regards,
Divy Srivastava

**Comment by DivySrivastava** [comment]
Hello @thiyaga24

We have a ready-to-use developer API for developers.
The api right now includes generating api keys and getting user info. New features coming soon.

Hope this will help!
Regards,
Divy Srivastava
