### ISSUE TITLE
Why /u/:id ? /u/:username is more appropriate

### ISSUE THREAD

**Issue by DivySrivastava** [dan-divy/spruce#38]
Using /u/:id should be reversed to /u/:username as users are shown according to their usernames.

**Comment by dan-online** [comment]
It broke sometimes with usernames because of special characters.

**Comment by dan-online** [comment]
spruce.divy.work user page is broken @DivySrivastava

**Comment by DivySrivastava** [comment]
Oh yeah..my bad...maybe we should go back to /:id thing.

**Comment by DivySrivastava** [comment]
Now we can change back to using `/:id` route.
Closing this issue.
