### ISSUE TITLE
dbHost not recognized

### ISSUE THREAD

**Issue by evan9523** [dan-divy/spruce#40]
Hi whenever i type in npm start it says "dbHost not recognized."

**Comment by DivySrivastava** [comment]
Hello @evan9523,
Thanks for opening the issue.

Could you please provide a screenshot or the full error displayed in the terminal?

**Comment by thisistuhinsen** [comment]
Hello I am having the same issue. 'db host' is not recognized as a command
screenshot attached
![error spruce db host](https://user-images.githubusercontent.com/53014388/61527081-4f314e80-aa39-11e9-8acd-bf7198b89282.png)

**Comment by dan-online** [comment]
Hi! @thisistuhinsen and @evan9523 in your package.json can you change 
```json
"scripts": {
    "start": "dbHost=localhost node ./bin/www"
  },
```
to 
```json
"scripts": {
    "start": "export dbHost=localhost; node ./bin/www"
  },
```

**Comment by thisistuhinsen** [comment]
Now its showing export not recognized as a command
![error spruce export](https://user-images.githubusercontent.com/53014388/61528279-f8794400-aa3b-11e9-855c-ffd24caa9643.png)

**Comment by dan-online** [comment]
@thisistuhinsen and @evan9523 change it to
```json
"scripts": {
    "start": "node ./bin/www"
  },
```

**Comment by dan-online** [comment]
Closing the issue as it has been resolved

**Comment by dan-online** [comment]
Also, spruce.divy.work user page is broken @DivySrivastava
