### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by dan-online** [dan-divy/spruce#42]
@DivySrivastava If you have a small amount of time then let's add some tests to make sure things are working such as the database is online etc etc. If you have more time tho work on git-chat

**Comment by DivySrivastava** [comment]
Sure! @dan-online 
So, how do plan to add the tests?

**Comment by dan-online** [comment]
Shall we use [mocha](https://mochajs.org/)?

**Comment by DivySrivastava** [comment]
Sure!

**Comment by DivySrivastava** [comment]
Add some tests in this commit 8c00f1ec03c114c7db261ac44b3384b9c92c2af3.
Use `npm test` to run!
