### ISSUE TITLE
V5 Discussion and Overview

### ISSUE THREAD

**Issue by divy-work** [dan-divy/spruce#49]
# Project Oak

Here, we update the list as we complete milestones and discuss on them.

List
* Use Vuejs for SPA
* Electron app (WIP - dan-online)

**Comment by DivySrivastava** [comment]
@dan-online,
@rburckner's version is structured very different that the existing one. We can consider his version as a whole rewrite and push the existing spruce to another branch named "old"

**Comment by dan-online** [comment]
Ok first let me move the app stuff over to a new branch alone because I’m adding downloading spruce into the app, I’ll text you when I’m ready

**Comment by divy-work** [comment]
@dan-online Should this be closed...since it lost momentum.

**Comment by dan-online** [comment]
Yep this is just [dan-divy/sea-horse](https://github.com/dan-divy/sea-horse)
