### ISSUE TITLE
Like/Comment errors

### ISSUE THREAD

**Issue by dan-online** [dan-divy/spruce#57]
@DivySrivastava, when someone changes their username the comment and like breaks, I don't get your system but I *, think* you do it by username when we should do it by ID, also a post username stays as the old one

**Comment by DivySrivastava** [comment]
@dan-online I always wanted to fix this, but I got distracted...yeah you got it right, we should use ID instead of Username.
If you can fix it it would be great, or else I'll fix it really soon.

**Comment by dan-online** [comment]
@DivySrivastava project-oak or master? Like I wanna fix master but it would cause conflics

**Comment by DivySrivastava** [comment]
@dan-online I guess we should make changes to project-oak...cause anyways we will have to depreciate the master branch
